language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - hhvm
#  - nightly

install:
    - git clone https://github.com/sstephenson/bats.git ${HOME}/bats_git; ${HOME}/bats_git/install.sh ${HOME}/bats
    - pear channel-discover pear.phing.info
    - pear install phing/phing
    - pear channel-discover pear.propelorm.org
    - pear install -a propel/propel_runtime
    - pear install Log
    - pear install Console_CommandLine
      #- pear install Console_Table
    - pear install channel://pear.php.net/Console_ProgressBar-0.5.2beta
    - echo 'phar.readonly = Off' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - ALLOW_DROP_DATABASE="yes" tests/reset-db.sh
script: ALLOW_DROP_DATABASE="yes" BATS_BINARY=${HOME}/bats/bin/bats tests/run-scripts.sh
